# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o 1.o
LINKOBJ  = main.o 1.o
LIBS     = -L"C:/Portable/Dev-Cpp/MinGW64/lib" -L"C:/Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Portable/Dev-Cpp/MinGW64/include" -I"C:/Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Portable/Dev-Cpp/MinGW64/include" -I"C:/Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) -Og -g3 -std=c++11
CFLAGS   = $(INCS) -Og -g3 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

1.o: 1.cpp
	$(CPP) -c 1.cpp -o 1.o $(CXXFLAGS)
